#!/bin/bash

# Delete an entry from ~/.ssh/known_hosts
# Usage: sshdel <line_number>
function sshdel { perl -i -n -e "print unless (\$. == $1)" ~/.ssh/known_hosts; }

docker_clean_images() {
  docker images --no-trunc | grep none | awk '{print $3}' | xargs docker rmi -f
}

docker_clean_containers() {
  docker ps -aq | xargs docker rm
}

docker_delete_image() {
  docker images --no-trunc | grep $1 | awk '{print $3}' | xargs docker rmi -f
}

docker_killall() {
  docker kill $( docker ps -q )
}

docker_ip() {
  docker inspect --format='{{ .NetworkSettings.IPAddress }}' $1
}

docker_latest() {
  docker images | grep latest | sort
}

tmnew() {
  tmux new-session -s $1
}
