---
- name: Install Homebrew dependencies on Debian
  become: yes
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    state: present
  when: ansible_facts['os_family'] == "Debian"
  tags: [homebrew]

- name: Install Homebrew dependencies on RedHat
  become: yes
  dnf:
    name:
      - gcc
      - make
      - procps-ng
      - curl
      - file
      - git
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  tags: [homebrew]

- name: Create Homebrew directory with user ownership
  become: yes
  file:
    path: /home/linuxbrew
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: '0755'
  when: ansible_facts['os_family'] != "Darwin"
  tags: [homebrew]

- name: Check if Homebrew is installed
  shell: |
    command -v brew || test -f /opt/homebrew/bin/brew || test -f /usr/local/bin/brew || test -f /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_check
  failed_when: false
  changed_when: false
  tags: [homebrew]

- name: Install Homebrew
  shell: |
    NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_check.rc != 0
  tags: [homebrew]
