---
- name: remove legacy init.vim
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/nvim/init.vim"
    state: absent
  tags: [neovim, dotfiles]

- name: remove legacy vimrc.bundles
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/nvim/vimrc.bundles"
    state: absent
  tags: [neovim, dotfiles]

- name: remove legacy vim-plug
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/nvim/autoload/plug.vim"
    state: absent
  tags: [neovim, dotfiles]

- name: remove legacy plugged directory
  file:
    path: "{{ ansible_facts['user_dir'] }}/.config/nvim/plugged"
    state: absent
  tags: [neovim, dotfiles]

- name: deploy neovim config directory
  copy:
    src: "{{ playbook_dir }}/../dotfiles/config/nvim/"
    dest: "{{ ansible_facts['user_dir'] }}/.config/nvim/"
    force: yes
  tags: [neovim, dotfiles]
