---
- name: Clone NVM repository
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ ansible_facts['user_dir'] }}/.nvm"
    version: v0.40.1
  tags: [nvm]

- name: Install latest LTS Node via nvm and set as default
  shell: |
    export NVM_DIR="{{ ansible_facts['user_dir'] }}/.nvm"
    . "$NVM_DIR/nvm.sh"
    nvm install --lts
    nvm alias default 'lts/*'
  args:
    executable: /bin/bash
    creates: "{{ ansible_facts['user_dir'] }}/.nvm/alias/default"
  tags: [nvm]

- name: Deploy NVM shell configuration (Bash)
  copy:
    src: "{{ playbook_dir }}/../dotfiles/bashrc.d/nvm.sh"
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc.d/nvm.sh"
    force: yes
    mode: '0644'
  tags: [nvm, dotfiles]

- name: Deploy NVM shell configuration (Zsh)
  copy:
    src: "{{ playbook_dir }}/../dotfiles/zshrc.d/nvm.zsh"
    dest: "{{ ansible_facts['user_dir'] }}/.zshrc.d/nvm.zsh"
    force: yes
    mode: '0644'
  when: ansible_facts['os_family'] == "Darwin"
  tags: [nvm, dotfiles]
