---
- hosts: localhost
  vars:
    fedora_release: 30
  tasks:
    - name: dnf packages
      become: yes
      dnf:
        name:
          - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_release }}.noarch.rpm'
          - 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_release }}.noarch.rpm'
          - emacs
          - ffmpeg
          - gnome-shell-extension-no-topleft-hot-corner
          - gnome-tweaks
          - htop
          - neovim
          - snapd
          - strace
          - vlc
    - name: snap symlink (for classic)
      become: yes
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        owner: root
        group: root
        state: link
    - name: snap packages
      become: yes
      snap:
        name:
          - core
          - core18
          - postman
          - spotify
    - name: snap install intellij
      become: yes
      snap:
        name:
          - code
          - go
          - intellij-idea-community
          - slack
        classic: yes
    - name: bashrc
      copy:
        src: ../dotfiles/bashrc
        dest: ~/.bashrc
        force: yes
    - name: bash_functions
      copy:
        src: ../dotfiles/bash_functions
        dest: ~/.bash_functions
        force: yes
    - name: bash_profile
      copy:
        src: ../dotfiles/bash_profile
        dest: ~/.bash_profile
        force: yes
    - name: bash_prompt
      copy:
        src: ../dotfiles/bash_prompt
        dest: ~/.bash_prompt
        force: yes
    - name: gitignore_global
      copy:
        src: ../dotfiles/gitignore_global
        dest: ~/.gitignore_global
        force: yes
    - name: pryrc
      copy:
        src: ../dotfiles/pryrc
        dest: ~/.pryrc
        force: yes
    - name: tmux.conf
      copy:
        src: ../dotfiles/tmux.conf
        dest: ~/.tmux.conf
        force: yes
    - name: spacemacs file
      copy:
        src: ../dotfiles/spacemacs
        dest: ~/.spacemacs
        force: yes
    - name: create nvim autoloads
      file:
        path: ~/.config/nvim/autoload
        state: directory
    - name: vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
    - name: install vim plugins
      command: vim +PlugInstall +qa
    - name: bash-my-aws
      git:
        repo: git@github.com:bash-my-universe/bash-my-aws.git
        dest: ~/.bash-my-aws
    - name: spacemacs
      git:
        repo: git@github.com:syl20bnr/spacemacs
        dest: ~/.emacs.d
