---
- hosts: localhost
  tasks:
    - name: dnf packages
      become: yes
      dnf:
        name:
          - gnome-tweaks
          - neovim
    - name: bashrc
      copy:
        src: ../dotfiles/bashrc
        dest: ~/.bashrc
        force: yes
    - name: bash_functions
      copy:
        src: ../dotfiles/bash_functions
        dest: ~/.bash_functions
        force: yes
    - name: bash_profile
      copy:
        src: ../dotfiles/bash_profile
        dest: ~/.bash_profile
        force: yes
    - name: bash_prompt
      copy:
        src: ../dotfiles/bash_prompt
        dest: ~/.bash_prompt
        force: yes
    - name: gitignore_global
      copy:
        src: ../dotfiles/gitignore_global
        dest: ~/.gitignore_global
        force: yes
    - name: pryrc
      copy:
        src: ../dotfiles/pryrc
        dest: ~/.pryrc
        force: yes
    - name: tmux.conf
      copy:
        src: ../dotfiles/tmux.conf
        dest: ~/.tmux.conf
        force: yes
    - name: create nvim autoloads
      file:
        path: ~/.config/nvim/autoload
        state: directory
    - name: vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
